sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t ewycheung/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ewycheung/docker-react npm run test -- --coverage